### ISSUE TITLE
`shared_iterator_test.cpp` from Utility needs to be moved here

### ISSUE THREAD

**Issue by pdimov** [boostorg/iterator#39]
It looks like we've moved `boost/shared_container_iterator.hpp` here, but forgot the test.

**Comment by eldiener** [comment]
It is only 15 years after the fact that you discovered this <g>. I agree we need some tests.

**Comment by pdimov** [comment]
Time flies, doesn't it?

Further careful inspection w/ glasses on reveals three example files and a documentation file, all sitting in `libs/utility` waiting to be awakened from their 15 year slumber.

**Comment by eldiener** [comment]
I had a smiley in the first line of my previous reply but somehow it was removed. In the docs I can see three examples also, as well as documentation already existing for shared_container_iterator in the iterator docs.

**Comment by pdimov** [comment]
The smiley did come across through e-mail, so all's not lost.

**Comment by pdimov** [comment]
The docs have apparently been ported to .qbk here, with the old .html still left there; the .qbk links the examples from libs/utility. :-)

**Comment by pdimov** [comment]
> I agree we need some tests.

On reflection, I'm not sure if you misinterpreted what I mean here; I'm saying that there's already a test, but it's in `libs/utility/test`, and just needs to be brought in (per the issue title).

**Comment by eldiener** [comment]
Do you really just want to remove the shared_iterator_test.cpp from 'utility' and add it to 'iterator' ? It uses 'assert' as its checking mechanism. That is not what I would call ideal. At leat it could use lightweight_test.hpp to do its checking. Also we probably want to at least add the examples, which are part of the 'iterator' documentation for shared_iterator as simple tests also.

**Comment by pdimov** [comment]
Done in https://github.com/boostorg/iterator/commit/218dc4baf173d09871757c9278e7b4eb4f9a3f52.
