### ISSUE TITLE
Usage of boost/utility/addressof.hpp ?

### ISSUE THREAD

**Issue by njlr** [boostorg/iterator#46]
I think this is now incorrect? 

https://github.com/boostorg/iterator/blob/develop/include/boost/iterator/iterator_facade.hpp#L19:

```
#include <boost/utility/addressof.hpp>
```

should be 

```
#include <boost/core/addressof.hpp>
```

https://github.com/boostorg/align/pull/3#issuecomment-48072039

**Comment by eldiener** [comment]
Both currently work, the former for backward compatibility.

**Comment by njlr** [comment]
I see. This header is in the `utility` folder, but is actaully part of boostorg/core. 

Thanks!
