### ISSUE TITLE
Post-increment operator fails on an rvalue iterator

### ISSUE THREAD

**Issue by shoreadmin** [boostorg/iterator#72]
We have a custom container and a `begin` function that produces a `iterator_facade`-derived type:
```cpp
Container c;

// This fails:
auto i = begin(c)++;

// This succeeds:
auto j = begin(c);
j++;
```

Could the `operator++` in the following code take a universal reference (`&&`) instead of a standard reference (`&`)?:
```cpp
  template <class I, class V, class TC, class R, class D>
  inline typename boost::iterators::detail::postfix_increment_result<I,V,R,TC>::type
  operator++(
      iterator_facade<I,V,TC,R,D>& i 
    , int
  )
  {
      typename boost::iterators::detail::postfix_increment_result<I,V,R,TC>::type
          tmp(*static_cast<I*>(&i));

      ++i;

      return tmp;
  }
```

**Comment by Lastique** [comment]
> ```
> auto i = begin(c)++;
> ```

You're discarding the result of increment here, `i` is initialized with `begin(c)` and not the incremented iterator. So I don't see a motivating example.

If you want to obtain an incremented/decremented iterator you can use `std::next`/`std::prev` or Boost [equivalents](https://github.com/boostorg/iterator/blob/d175ba245026adf22d7cea7d992079162f5110ea/include/boost/next_prior.hpp#L175-L191).
